# -*- coding: utf-8 -*-
"""fibromyalgia_diagnostics_random_forest_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Doy5WjGsSF3ajoRV7VFljQow5W2eeOMr

##### Template is based on the learning instructions from Machine Learning A-Z: AI, Python & R + ChatGPT Prize [2025] course

### Importing the libraries
"""

import numpy as np
import pandas as pd

"""### Importing the dataset"""

dataset = pd.read_csv('fibromyalgia_data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

"""### Dealing with missing data: 2 methods"""

dataset.dropna()

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 0:10])
X[:, 0:10] = imputer.transform(X[:, 0:10])

"""### Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

print(X_train)

print(y_train)

print(X_test)

print(y_test)

"""### Feature Scaling"""

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train)

print(X_test)

"""### Training the Random Forest Classification model"""

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

"""### Predicting a new result"""

print(classifier.predict(sc.transform([[2,2,2,4,7,2,2,7,7]])))

print(classifier.predict(sc.transform([[0,0,0,0,3,0,0,3,3]])))

"""### Predicting the Test set results"""

y_pred = classifier.predict(X_test)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

"""### Making the Confusion Matrix"""

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
accuracy_score(y_test, y_pred)

print(cm)